# Generated by Django 3.1.4 on 2020-12-23 22:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201224_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 22, 39, 28, 47755, tzinfo=utc)),
        ),
    ]
